version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  lint:
    executor:
      name: node/default
      tag: "lts"
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Run oxlint
          command: pnpm run lint
      - run:
          name: Run esbuild
          command: pnpm run build

  validate:
    docker:
      - image: ubuntu:18.04
    resource_class: small
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y make xsltproc libxml2-utils
      - checkout
      - run:
          name: Generate MBSE reports
          command: make -j
      - store_artifacts:
          path: static
      - store_artifacts:
          path: out
      - run:
          name: Validate MBSE model
          command: make validate

      - run:
          name: Validate MBSE model (clock-radio)
          command: make validate model_path=advanced_examples/clock-radio-capella/ -Bj

      - run:
          name: Validate MBSE model (drone)
          command: make validate model_path=advanced_examples/drone-doorstep/ -Bj

workflows:
  lint:
    jobs:
      - lint

  validate:
    jobs:
      - validate