# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y make xsltproc libxml2-utils
      - checkout
      - run:
          name: Generate MBSE reports
          command: make -j
      - store_artifacts:
          path: static
      - store_artifacts:
          path: out
      - run:
          name: Validate MBSE model
          command: make validate
